import { z } from "zod";

export const API_ERROR_CODE = {
  VALIDATION: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  INTERNAL: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  EQUIPMENT_NAME_EXISTS: "EQUIPMENT_NAME_EXISTS",
  EMPLOYEE_EMAIL_EXISTS: "EMPLOYEE_EMAIL_EXISTS",
  LOCATION_NAME_EXISTS: "LOCATION_NAME_EXISTS",
  MULTIPLE_LOCATIONS_DISABLED: "MULTIPLE_LOCATIONS_DISABLED",
  DEFAULT_LOCATION_DELETE_FORBIDDEN: "DEFAULT_LOCATION_DELETE_FORBIDDEN",
  LAST_LOCATION_DELETE_FORBIDDEN: "LAST_LOCATION_DELETE_FORBIDDEN",
  LOCATION_HAS_DEPENDENCIES: "LOCATION_HAS_DEPENDENCIES",
  TASK_RECORD_ALREADY_EXISTS: "TASK_RECORD_ALREADY_EXISTS",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];

export const apiErrorSchema = z.object({
  error: z.string(),
  message: z.string(),
  details: z.unknown().optional(),
  requestId: z.string(),
});

export type ApiError = z.infer<typeof apiErrorSchema>;
